# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3e485f07effd6ba12696e86ca5b6625e45ee1115b4248853a928f1b8910940dc03bd827be7b78204fdf0bbd8937cda285edb631835e1944ba37af7f2df16352

test:
  secret_key_base: a83bca7d99cad19ecbc5b00711d33ec78cf72f59250cb390fe5902f4b5e88f33d79bfb39826e3f3ad3304ff72180c7063b19a330d1fef676de1f2594ef126afb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
